### ISSUE TITLE
crash report to check

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#242]
APP_VERSION_CODE=65
APP_VERSION_NAME=4.2.0
ANDROID_VERSION=4.1.1
PHONE_MODEL=EVO
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at eu.geopaparazzi.library.sensors.OrientationSensor.onSensorChanged(OrientationSensor.java:158)
at android.hardware.SystemSensorManager$ListenerDelegate$1.handleMessage(SystemSensorManager.java:210)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5454)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
at dalvik.system.NativeStart.main(Native Method)

**Comment by moovida** [comment]
APP_VERSION_CODE=65
APP_VERSION_NAME=4.2.0
ANDROID_VERSION=4.2.2
PHONE_MODEL=JY-G4
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at eu.geopaparazzi.library.sensors.OrientationSensor.onSensorChanged(OrientationSensor.java:158)
at android.hardware.SystemSensorManager$ListenerDelegate$1.handleMessage(SystemSensorManager.java:261)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5560)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
at dalvik.system.NativeStart.main(Native Method)

**Comment by moovida** [comment]
fixed
