### ISSUE TITLE
crash report to check II

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#244]
APP_VERSION_CODE=64
APP_VERSION_NAME=4.1.1
ANDROID_VERSION=4.4.2
PHONE_MODEL=H60-L04
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.GeoPaparazziActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3035)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3064)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2350)
        at android.app.ActivityThread.access$1100(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.initVars(ActionBar.java:132)
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.<init>(ActionBar.java:99)
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.getActionBar(ActionBar.java:158)
        at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.checkActionBar(GeoPaparazziActivity.java:333)
        at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.onResume(GeoPaparazziActivity.java:317)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1200)
        at android.app.Activity.performResume(Activity.java:5365)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3008)
        ... 12 more
java.lang.NullPointerException
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.initVars(ActionBar.java:132)
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.<init>(ActionBar.java:99)
        at eu.hydrologis.geopaparazzi.dashboard.ActionBar.getActionBar(ActionBar.java:158)
        at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.checkActionBar(GeoPaparazziActivity.java:333)
        at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.onResume(GeoPaparazziActivity.java:317)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1200)
        at android.app.Activity.performResume(Activity.java:5365)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3008)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3064)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2350)
        at android.app.ActivityThread.access$1100(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by moovida** [comment]
fixed
