### ISSUE TITLE
crash report to check III

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#245]
Provato a cambiare la cartella per le mappe offline dalla memoria interna alla scheda sd. 
Ho cambiato smartphone, precedentemente nessun problema

APP_VERSION_CODE=58
APP_VERSION_NAME=3.9.7
ANDROID_VERSION=4.4.2
PHONE_MODEL=LG-D620
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.GeoPaparazziActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2797)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2826)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
at android.app.ActivityThread.access$800(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.initVars(ActionBar.java:134)
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.<init>(ActionBar.java:94)
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.getActionBar(ActionBar.java:157)
at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.checkActionBar(GeoPaparazziActivity.java:293)
at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.onResume(GeoPaparazziActivity.java:277)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
at android.app.Activity.performResume(Activity.java:5354)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2787)
... 12 more
java.lang.NullPointerException
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.initVars(ActionBar.java:134)
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.<init>(ActionBar.java:94)
at eu.hydrologis.geopaparazzi.dashboard.ActionBar.getActionBar(ActionBar.java:157)
at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.checkActionBar(GeoPaparazziActivity.java:293)
at eu.hydrologis.geopaparazzi.GeoPaparazziActivity.onResume(GeoPaparazziActivity.java:277)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
at android.app.Activity.performResume(Activity.java:5354)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2787)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2826)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
at android.app.ActivityThread.access$800(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)

**Comment by moovida** [comment]
fixed
