### ISSUE TITLE
Still crashes on Sensor Orientation

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#247]
APP_VERSION_CODE=67
APP_VERSION_NAME=4.2.2
ANDROID_VERSION=4.1.2
PHONE_MODEL=LT22i
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at eu.geopaparazzi.library.sensors.OrientationSensor.onSensorChanged(OrientationSensor.java:161)
at android.hardware.SystemSensorManager$ListenerDelegate$1.handleMessage(SystemSensorManager.java:204)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4744)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

**Comment by moovida** [comment]
Fixed
