### ISSUE TITLE
mock permission missing for demo

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#313]
APP_VERSION_CODE=73
APP_VERSION_NAME=5.0.0
ANDROID_VERSION=5.1.1
PHONE_MODEL=D6603
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start service eu.geopaparazzi.library.gps.GpsService@564a3bc with Intent { cmp=eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.gps.GpsService }: java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION permission
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2975)
at android.app.ActivityThread.access$2100(ActivityThread.java:156)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5373)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION permission
at android.os.Parcel.readException(Parcel.java:1553)
at android.os.Parcel.readException(Parcel.java:1505)
at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:1054)
at android.location.LocationManager.addTestProvider(LocationManager.java:1216)
at eu.geopaparazzi.library.util.debug.TestMock.startMocking(TestMock.java:75)
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:284)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:210)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2958)
... 9 more
java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION permission
at android.os.Parcel.readException(Parcel.java:1553)
at android.os.Parcel.readException(Parcel.java:1505)
at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:1054)
at android.location.LocationManager.addTestProvider(LocationManager.java:1216)
at eu.geopaparazzi.library.util.debug.TestMock.startMocking(TestMock.java:75)
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:284)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:210)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2958)
at android.app.ActivityThread.access$2100(ActivityThread.java:156)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5373)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by moovida** [comment]
fixed
