### ISSUE TITLE
Directory browser crash

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#314]
APP_VERSION_CODE=73
APP_VERSION_NAME=5.0.0
ANDROID_VERSION=5.0.1
PHONE_MODEL=ALE-L02
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity}: java.lang.NullPointerException: Attempt to get length of null array
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
at android.app.ActivityThread.access$1200(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.endsWith(DirectoryBrowserActivity.java:287)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.access$200(DirectoryBrowserActivity.java:69)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity$1.accept(DirectoryBrowserActivity.java:133)
at java.io.File.listFiles(File.java:828)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.onCreate(DirectoryBrowserActivity.java:168)
at android.app.Activity.performCreate(Activity.java:6013)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
... 10 more
java.lang.NullPointerException: Attempt to get length of null array
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.endsWith(DirectoryBrowserActivity.java:287)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.access$200(DirectoryBrowserActivity.java:69)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity$1.accept(DirectoryBrowserActivity.java:133)
at java.io.File.listFiles(File.java:828)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.onCreate(DirectoryBrowserActivity.java:168)
at android.app.Activity.performCreate(Activity.java:6013)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
at android.app.ActivityThread.access$1200(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)

**Comment by moovida** [comment]
fixed
