### ISSUE TITLE
error from ACRA 

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#318]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=5.0.1
PHONE_MODEL=ALE-L02
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'jsqlite.Database eu.geopaparazzi.spatialite.database.spatial.core.databasehandlers.SpatialiteDatabaseHandler.getDatabase()' on a null object reference
at eu.hydrologis.geopaparazzi.maptools.FeatureUtilities.buildWithoutGeometry(FeatureUtilities.java:103)
at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doBackgroundWork(InfoTool.java:229)
at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:115)
at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:58)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.lang.NullPointerException: Attempt to invoke virtual method 'jsqlite.Database eu.geopaparazzi.spatialite.database.spatial.core.databasehandlers.SpatialiteDatabaseHandler.getDatabase()' on a null object reference
at eu.hydrologis.geopaparazzi.maptools.FeatureUtilities.buildWithoutGeometry(FeatureUtilities.java:103)
at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doBackgroundWork(InfoTool.java:229)
at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:115)
at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:58)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:831)

**Comment by moovida** [comment]
done
