### ISSUE TITLE
error from ACRA -  invalid latitude

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#319]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=4.4.2
PHONE_MODEL=ASUS_T00F
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalArgumentException: invalid latitude: 2147.483647
at org.mapsforge.core.model.Coordinates.validateLatitude(Coordinates.java:121)
at org.mapsforge.core.model.GeoPoint.validateCoordinates(GeoPoint.java:68)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:104)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:94)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.setNewCenterAtZoom(MapviewActivity.java:603)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onWindowFocusChanged(MapviewActivity.java:563)
at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:115)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:2677)
at android.view.View.dispatchWindowFocusChanged(View.java:8009)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:968)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3160)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:149)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)

LOGCAT=--------- beginning of /dev/log/system
--------- beginning of /dev/log/main

**Comment by moovida** [comment]
fixed
