### ISSUE TITLE
error from ACRA -  tantomapurls

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#320]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=5.1.1
PHONE_MODEL=Redmi 3
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.app.Dialog.<init>(Dialog.java:108)
at android.app.AlertDialog.<init>(AlertDialog.java:125)
at android.app.AlertDialog.<init>(AlertDialog.java:109)
at android.app.ProgressDialog.<init>(ProgressDialog.java:77)
at eu.geopaparazzi.library.util.StringAsyncTask.onPreExecute(StringAsyncTask.java:93)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
at android.os.AsyncTask.execute(AsyncTask.java:539)
at eu.hydrologis.geopaparazzi.ui.activities.tantomapurls.TantoMapurlsListActivity.downloadProject(TantoMapurlsListActivity.java:237)
at eu.hydrologis.geopaparazzi.ui.activities.tantomapurls.TantoMapurlsListActivity.access$100(TantoMapurlsListActivity.java:60)
at eu.hydrologis.geopaparazzi.ui.activities.tantomapurls.TantoMapurlsListActivity$1$1$1.run(TantoMapurlsListActivity.java:165)
at java.lang.Thread.run(Thread.java:818)

**Comment by moovida** [comment]
fixed
