### ISSUE TITLE
error from ACRA -  invalid latitude 2

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#321]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=5.0.2
PHONE_MODEL=A0001
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.mapview.MapviewActivity}: java.lang.IllegalArgumentException: invalid latitude: 2147.483647
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
at android.app.ActivityThread.access$900(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5238)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
Caused by: java.lang.IllegalArgumentException: invalid latitude: 2147.483647
at org.mapsforge.core.model.Coordinates.validateLatitude(Coordinates.java:121)
at org.mapsforge.core.model.GeoPoint.validateCoordinates(GeoPoint.java:68)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:104)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:94)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.setNewCenterAtZoom(MapviewActivity.java:603)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:340)
at android.app.Activity.performCreate(Activity.java:5941)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
... 10 more
java.lang.IllegalArgumentException: invalid latitude: 2147.483647
at org.mapsforge.core.model.Coordinates.validateLatitude(Coordinates.java:121)
at org.mapsforge.core.model.GeoPoint.validateCoordinates(GeoPoint.java:68)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:104)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:94)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.setNewCenterAtZoom(MapviewActivity.java:603)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:340)
at android.app.Activity.performCreate(Activity.java:5941)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
at android.app.ActivityThread.access$900(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5238)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

LOGCAT=--------- beginning of main
--------- beginning of system

**Comment by moovida** [comment]
fixed
