### ISSUE TITLE
error from ACRA - https - should be solved already

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#322]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=6.0
PHONE_MODEL=MotoG3
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
at eu.hydrologis.geopaparazzi.ui.activities.ImportActivity.onWMSLayersAdded(ImportActivity.java:369)
at gov.nasa.worldwind.AddWMSDialog$3.onClick(AddWMSDialog.java:171)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

LOGCAT=--------- beginning of system
--------- beginning of main

More information for wms import crash

WMS: 
http://ogc.larioja.org/wms/request.php
LAYER: arboles singulares

**Comment by moovida** [comment]
solved
