### ISSUE TITLE
error from ACRA - KmzExportDialogFragment

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#323]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=6.0.1
PHONE_MODEL=Nexus 7
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Fragment KmzExportDialogFragment{506d2c6} not attached to Activity
at android.support.v4.app.Fragment.getResources(Fragment.java:636)
at android.support.v4.app.Fragment.getString(Fragment.java:658)
at eu.hydrologis.geopaparazzi.ui.dialogs.KmzExportDialogFragment$3.onPostExecute(KmzExportDialogFragment.java:226)
at eu.hydrologis.geopaparazzi.ui.dialogs.KmzExportDialogFragment$3.onPostExecute(KmzExportDialogFragment.java:130)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
done
