### ISSUE TITLE
error from ACRA - mapsforge problem

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#324]
APP_VERSION_CODE=74
APP_VERSION_NAME=5.0.1
ANDROID_VERSION=4.4.2
PHONE_MODEL=AxonFone_A4
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.mapview.MapviewActivity}: java.lang.IllegalArgumentException: could not create directory: /storage/sdcard0/Android/data/org.mapsforge.android.maps/cache/1
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: could not create directory: /storage/sdcard0/Android/data/org.mapsforge.android.maps/cache/1
at org.mapsforge.android.maps.mapgenerator.FileSystemTileCache.createDirectory(FileSystemTileCache.java:81)
at org.mapsforge.android.maps.mapgenerator.FileSystemTileCache.<init>(FileSystemTileCache.java:211)
at org.mapsforge.android.maps.MapView.<init>(MapView.java:153)
at org.mapsforge.android.maps.MapView.<init>(MapView.java:112)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:265)
at android.app.Activity.performCreate(Activity.java:5264)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
... 11 more
java.lang.IllegalArgumentException: could not create directory: /storage/sdcard0/Android/data/org.mapsforge.android.maps/cache/1
at org.mapsforge.android.maps.mapgenerator.FileSystemTileCache.createDirectory(FileSystemTileCache.java:81)
at org.mapsforge.android.maps.mapgenerator.FileSystemTileCache.<init>(FileSystemTileCache.java:211)
at org.mapsforge.android.maps.MapView.<init>(MapView.java:153)
at org.mapsforge.android.maps.MapView.<init>(MapView.java:112)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:265)
at android.app.Activity.performCreate(Activity.java:5264)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)

LOGCAT=--------- beginning of /dev/log/main
--------- beginning of /dev/log/system

**Comment by moovida** [comment]
fixed
