### ISSUE TITLE
error from ACRA - CopyToLayersListActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#330]
APP_VERSION_CODE=75
APP_VERSION_NAME=5.0.2
ANDROID_VERSION=5.0.2
PHONE_MODEL=SM-T715
CUSTOM_DATA=
STACK_TRACE=android.content.ActivityNotFoundException: Unable to find explicit activity class {eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.maptools.CopyToLayersListActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1499)
at android.app.Activity.startActivityForResult(Activity.java:3954)
at android.app.Activity.startActivityForResult(Activity.java:3901)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4225)
at android.app.Activity.startActivity(Activity.java:4193)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonOnSelectionToolGroup.onClick(PolygonOnSelectionToolGroup.java:244)
at android.view.View.performClick(View.java:5210)
at android.view.View$PerformClick.run(View.java:20976)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6145)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by moovida** [comment]
fixed
