### ISSUE TITLE
error from ACRA - unknown geometry type

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#331]
APP_VERSION_CODE=75
APP_VERSION_NAME=5.0.2
ANDROID_VERSION=5.0.2
PHONE_MODEL=SM-T715
CUSTOM_DATA=
STACK_TRACE=com.vividsolutions.jts.util.AssertionFailedException: Should never reach here: Unknown Geometry type
at com.vividsolutions.jts.util.Assert.shouldNeverReachHere(Assert.java:122)
at com.vividsolutions.jts.io.WKBWriter.write(WKBWriter.java:336)
at com.vividsolutions.jts.io.WKBWriter.write(WKBWriter.java:299)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool.getProcessedFeatures(PolygonCutExtendTool.java:347)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonMainEditingToolGroup.onToolFinished(PolygonMainEditingToolGroup.java:337)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool$1.onPostExecute(PolygonCutExtendTool.java:329)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool$1.onPostExecute(PolygonCutExtendTool.java:266)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6145)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by moovida** [comment]
fixed, but without being able to reproduce the problem in first place. Let's see if it works
