### ISSUE TITLE
error from ACRA - dashed lines

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#334]
APP_VERSION_CODE=75
APP_VERSION_NAME=5.0.2
ANDROID_VERSION=5.0.1
PHONE_MODEL=ALE-L02
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to get length of null array
at eu.geopaparazzi.library.style.Style.dashToString(Style.java:200)
at eu.geopaparazzi.spatialite.database.spatial.activities.databasesview.SpatialiteDatabasesExpandableListAdapter.onDashChanged(SpatialiteDatabasesExpandableListAdapter.java:440)
at eu.geopaparazzi.spatialite.database.spatial.activities.databasesview.SpatialiteDatabasesTreeListActivity.onDashChanged(SpatialiteDatabasesTreeListActivity.java:438)
at eu.geopaparazzi.library.core.dialogs.StrokeDashDialogFragment$1.onClick(StrokeDashDialogFragment.java:149)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by moovida** [comment]
fixed
