### ISSUE TITLE
error from ACRA - .aseMapSourcesManager.getSelectedBaseMapTable

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#336]
APP_VERSION_CODE=75
APP_VERSION_NAME=5.0.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=GT-I9100
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.mapview.MapviewActivity}: java.util.NoSuchElementException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:343)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.loadSelectedBaseMap(BaseMapSourcesManager.java:391)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:276)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
... 9 more
java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:343)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.loadSelectedBaseMap(BaseMapSourcesManager.java:391)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:276)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by moovida** [comment]
fixed
