### ISSUE TITLE
From ACRA: ActivityNotFoundException

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#339]
APP_VERSION_CODE=76
APP_VERSION_NAME=5.1.0
ANDROID_VERSION=5.0.2
PHONE_MODEL=SM-A300G
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Could not execute method for android:onClick
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
at android.view.View.performClick(View.java:5044)
at android.view.View$PerformClick.run(View.java:20154)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5536)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
... 10 more
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.core.fragments.DatabaseListFragment}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1769)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
at android.app.Activity.startActivityForResult(Activity.java:3796)
at android.app.Activity.startActivityForResult(Activity.java:3744)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4067)
at android.app.Activity.startActivity(Activity.java:4035)
at eu.hydrologis.geopaparazzi.ui.activities.SqlViewActivity.launchOwnQuery(SqlViewActivity.java:104)
... 13 more
java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
at android.view.View.performClick(View.java:5044)
at android.view.View$PerformClick.run(View.java:20154)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5536)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.core.fragments.DatabaseListFragment}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1769)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
at android.app.Activity.startActivityForResult(Activity.java:3796)
at android.app.Activity.startActivityForResult(Activity.java:3744)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4067)
at android.app.Activity.startActivity(Activity.java:4035)
at eu.hydrologis.geopaparazzi.ui.activities.SqlViewActivity.launchOwnQuery(SqlViewActivity.java:104)
... 13 more
android.content.ActivityNotFoundException: Unable to find explicit activity class {eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.core.fragments.DatabaseListFragment}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1769)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
at android.app.Activity.startActivityForResult(Activity.java:3796)
at android.app.Activity.startActivityForResult(Activity.java:3744)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4067)
at android.app.Activity.startActivity(Activity.java:4035)
at eu.hydrologis.geopaparazzi.ui.activities.SqlViewActivity.launchOwnQuery(SqlViewActivity.java:104)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
at android.view.View.performClick(View.java:5044)
at android.view.View$PerformClick.run(View.java:20154)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5536)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)

**Comment by moovida** [comment]
fixed in changeset 58fc3b2
