### ISSUE TITLE
From ACRA: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#340]
APP_VERSION_CODE=76
APP_VERSION_NAME=5.1.0
ANDROID_VERSION=6.0.1
PHONE_MODEL=A0001
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.GeopaparazziActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at eu.geopaparazzi.library.permissions.PermissionWriteStorage.hasGainedPermission(PermissionWriteStorage.java:95)
at eu.hydrologis.geopaparazzi.GeopaparazziActivity.onRequestPermissionsResult(GeopaparazziActivity.java:158)
at android.app.Activity.requestPermissions(Activity.java:3823)
at eu.geopaparazzi.library.permissions.PermissionWriteStorage.requestPermission(PermissionWriteStorage.java:83)
at eu.hydrologis.geopaparazzi.GeopaparazziActivity.onCreate(GeopaparazziActivity.java:74)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
... 9 more
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at eu.geopaparazzi.library.permissions.PermissionWriteStorage.hasGainedPermission(PermissionWriteStorage.java:95)
at eu.hydrologis.geopaparazzi.GeopaparazziActivity.onRequestPermissionsResult(GeopaparazziActivity.java:158)
at android.app.Activity.requestPermissions(Activity.java:3823)
at eu.geopaparazzi.library.permissions.PermissionWriteStorage.requestPermission(PermissionWriteStorage.java:83)
at eu.hydrologis.geopaparazzi.GeopaparazziActivity.onCreate(GeopaparazziActivity.java:74)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by moovida** [comment]
fixed
