### ISSUE TITLE
From ACRA: ConcurrentModificationException

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#342]
APP_VERSION_CODE=76
APP_VERSION_NAME=5.1.0
ANDROID_VERSION=6.0.1
PHONE_MODEL=SM-N910F
CUSTOM_DATA=
STACK_TRACE=java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at eu.hydrologis.geopaparazzi.mapview.overlays.GeopaparazziOverlay.drawFromSpatialite(GeopaparazziOverlay.java:627)
at eu.hydrologis.geopaparazzi.mapview.overlays.GeopaparazziOverlay.drawOverlayBitmap(GeopaparazziOverlay.java:384)
at org.mapsforge.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:318)
at org.mapsforge.android.maps.overlay.Overlay.run(Overlay.java:250)

LOGCAT=--------- beginning of main
--------- beginning of system

**Comment by moovida** [comment]
Fixed for now
