### ISSUE TITLE
From ACRA: WebProjectsListActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#343]
APP_VERSION_CODE=76
APP_VERSION_NAME=5.1.0
ANDROID_VERSION=6.0.1
PHONE_MODEL=Nexus 6P
CUSTOM_DATA=
STACK_TRACE=android.content.ActivityNotFoundException: Unable to find explicit activity class {eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.webproject.WebProjectsListActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
at android.app.Activity.startActivityForResult(Activity.java:3930)
at android.app.Activity.startActivityForResult(Activity.java:3890)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
at android.app.Activity.startActivity(Activity.java:4213)
at android.app.Activity.startActivity(Activity.java:4181)
at eu.hydrologis.geopaparazzi.ui.activities.ImportActivity$3.onClick(ImportActivity.java:129)
at android.view.View.performClick(View.java:5204)
at android.view.View$PerformClick.run(View.java:21155)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
fixed
