### ISSUE TITLE
From ACRA: NPE  KmzExportDialogFragment

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#346]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=GT-I9100
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method &#39;java.lang.String android.support.v4.app.FragmentActivity.getString(int)&#39; on a null object reference
at eu.hydrologis.geopaparazzi.ui.dialogs.KmzExportDialogFragment$3.onPostExecute(KmzExportDialogFragment.java:226)
at eu.hydrologis.geopaparazzi.ui.dialogs.KmzExportDialogFragment$3.onPostExecute(KmzExportDialogFragment.java:130)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by moovida** [comment]
done
