### ISSUE TITLE
From ACRA: DirectoryBrowserActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#347]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=5.1.1
PHONE_MODEL=LG-H955
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.goUp(DirectoryBrowserActivity.java:205)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.access$600(DirectoryBrowserActivity.java:69)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity$3.onClick(DirectoryBrowserActivity.java:163)
at android.view.View.performClick(View.java:4788)
at android.view.View$PerformClick.run(View.java:19965)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5431)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by moovida** [comment]
done
