### ISSUE TITLE
From ACRA: GpxExportDialogFragment

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#349]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=A0001
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Fragment GpxExportDialogFragment{dde7bb1} not attached to Activity
at android.support.v4.app.Fragment.getResources(Fragment.java:636)
at android.support.v4.app.Fragment.getString(Fragment.java:658)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpxExportDialogFragment$3.onPostExecute(GpxExportDialogFragment.java:182)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpxExportDialogFragment$3.onPostExecute(GpxExportDialogFragment.java:125)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main
--------- beginning of system

**Comment by moovida** [comment]
done
