### ISSUE TITLE
From ACRA: GpsDataListActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#350]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=4.4.2
PHONE_MODEL=GT-N7100
CUSTOM_DATA=
STACK_TRACE=android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6986)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1102)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4529)
at android.view.View.invalidate(View.java:11661)
at android.view.View.invalidate(View.java:11615)
at android.widget.AbsListView.resetList(AbsListView.java:2408)
at android.widget.ListView.resetList(ListView.java:527)
at android.widget.ListView.setAdapter(ListView.java:468)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity.refreshList(GpsDataListActivity.java:316)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity.access$100(GpsDataListActivity.java:78)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity$4.run(GpsDataListActivity.java:408)
at java.lang.Thread.run(Thread.java:841)

LOGCAT=--------- beginning of /dev/log/main

**Comment by moovida** [comment]
done
