### ISSUE TITLE
From ACRA:  invalid latitude: 2147.483647

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#354]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=A0001
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalArgumentException: invalid latitude: 2147.483647
at org.mapsforge.core.model.Coordinates.validateLatitude(Coordinates.java:121)
at org.mapsforge.core.model.GeoPoint.validateCoordinates(GeoPoint.java:68)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:104)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:94)
at eu.hydrologis.geopaparazzi.database.DaoNotes.getNoteOverlaysList(DaoNotes.java:408)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.readData(MapviewActivity.java:494)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onWindowFocusChanged(MapviewActivity.java:568)
at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:115)
at com.android.internal.policy.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:3493)
at android.view.View.dispatchWindowFocusChanged(View.java:9535)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1200)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3386)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by moovida** [comment]
done
