### ISSUE TITLE
From ACRA:  not attached to window manager

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#355]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=Nexus 7
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{94ebf02 V.E...... R.....ID 0,0-959,232} not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
at android.app.Dialog.dismissDialog(Dialog.java:362)
at android.app.Dialog.dismiss(Dialog.java:345)
at eu.geopaparazzi.library.util.StringAsyncTask.onPostExecute(StringAsyncTask.java:126)
at eu.geopaparazzi.library.util.StringAsyncTask.onPostExecute(StringAsyncTask.java:58)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main
--------- beginning of system

**Comment by moovida** [comment]
done
