### ISSUE TITLE
From ACRA:  Error receiving broadcast Intent

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#356]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=GT-N7100
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Error receiving broadcast Intent { act=eu.geopaparazzi.library.gps.GpsService flg=0x10 (has extras) } in eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment$2@82bf160
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:892)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:350)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment.onGpsServiceUpdate(GpsInfoDialogFragment.java:132)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment.access$000(GpsInfoDialogFragment.java:52)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment$2.onReceive(GpsInfoDialogFragment.java:91)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
... 7 more
java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:350)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment.onGpsServiceUpdate(GpsInfoDialogFragment.java:132)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment.access$000(GpsInfoDialogFragment.java:52)
at eu.hydrologis.geopaparazzi.ui.dialogs.GpsInfoDialogFragment$2.onReceive(GpsInfoDialogFragment.java:91)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
done
