### ISSUE TITLE
From ACRA: CalledFromWrongThreadException

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#358]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=5.1
PHONE_MODEL=XT1033
CUSTOM_DATA=
STACK_TRACE=android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6462)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:932)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4692)
at android.view.View.invalidateInternal(View.java:11806)
at android.view.View.invalidate(View.java:11742)
at android.view.View.invalidateDrawable(View.java:15843)
at android.widget.TextView.invalidateDrawable(TextView.java:5138)
at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:368)
at android.graphics.drawable.RippleDrawable.invalidateSelf(RippleDrawable.java:643)
at android.graphics.drawable.RippleDrawable.jumpToCurrentState(RippleDrawable.java:217)
at android.view.View.jumpDrawablesToCurrentState(View.java:16188)
at android.widget.TextView.jumpDrawablesToCurrentState(TextView.java:5059)
at android.widget.CompoundButton.jumpDrawablesToCurrentState(CompoundButton.java:460)
at android.view.View.onDetachedFromWindowInternal(View.java:13427)
at android.widget.TextView.onDetachedFromWindowInternal(TextView.java:5001)
at android.view.View.dispatchDetachedFromWindow(View.java:13579)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4400)
at android.widget.AbsListView.resetList(AbsListView.java:1986)
at android.widget.ListView.resetList(ListView.java:528)
at android.widget.ListView.setAdapter(ListView.java:469)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity.refreshList(GpsDataListActivity.java:316)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity.access$100(GpsDataListActivity.java:78)
at eu.hydrologis.geopaparazzi.ui.activities.GpsDataListActivity$4.run(GpsDataListActivity.java:408)
at java.lang.Thread.run(Thread.java:818)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
duplicate
