### ISSUE TITLE
From ACRA: NullPointerException

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#359]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=ASUS_Z016D
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
at eu.geopaparazzi.library.core.maps.BaseMap.hashCode(BaseMap.java:114)
at java.util.Collections.secondaryHash(Collections.java:3427)
at java.util.HashMap.get(HashMap.java:300)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.setSelectedBaseMap(BaseMapSourcesManager.java:371)
at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$3.onChildClick(SourcesTreeListActivity.java:329)
at android.widget.ExpandableListView.handleItemClick(ExpandableListView.java:717)
at android.widget.ExpandableListView.performItemClick(ExpandableListView.java:656)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
at android.widget.AbsListView$3.run(AbsListView.java:3903)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5451)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of system
--------- beginning of main

**Comment by moovida** [comment]
done
