### ISSUE TITLE
FROM ACRA DirectoryBrowserActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#373]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=5.1
PHONE_MODEL=unknown
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.goUp(DirectoryBrowserActivity.java:205)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.access$600(DirectoryBrowserActivity.java:69)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity$3.onClick(DirectoryBrowserActivity.java:163)
at android.view.View.performClick(View.java:4848)
at android.view.View$PerformClick.run(View.java:20262)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5631)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
duplicate of #347
