### ISSUE TITLE
FROM ACRA: Aplicación Crash when I browse Maps directory pushing plus Butrón

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#374]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=4.4.2
PHONE_MODEL=bq Edison 2 Quad Core 3G
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.goUp(DirectoryBrowserActivity.java:205)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity.access$600(DirectoryBrowserActivity.java:69)
at eu.geopaparazzi.library.core.activities.DirectoryBrowserActivity$3.onClick(DirectoryBrowserActivity.java:163)
at android.view.View.performClick(View.java:4443)
at android.view.View$PerformClick.run(View.java:18443)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
at dalvik.system.NativeStart.main(Native Method)

LOGCAT=--------- beginning of /dev/log/system
--------- beginning of /dev/log/main

Aplicación Crash when I browse Maps directory pushing plus Butrón. Some  mbtiles exist in directory but are missing.

**Comment by moovida** [comment]
done
