### ISSUE TITLE
FROM ACRA: Geometry.toText()' on a null object reference

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#375]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=Aquaris X5 Plus
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.vividsolutions.jts.geom.Geometry.toText()' on a null object reference
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool.getProcessedFeatures(PolygonCutExtendTool.java:353)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonMainEditingToolGroup.onToolFinished(PolygonMainEditingToolGroup.java:340)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool$1.onPostExecute(PolygonCutExtendTool.java:329)
at eu.hydrologis.geopaparazzi.maptools.tools.PolygonCutExtendTool$1.onPostExecute(PolygonCutExtendTool.java:266)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.access$500(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of system
--------- beginning of main

**Comment by moovida** [comment]
solved
