### ISSUE TITLE
FROM ACRA: basemap selection

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#376]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=4.4.2
PHONE_MODEL=PSP3502DUO
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.mapview.MapviewActivity}: java.util.NoSuchElementException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:808)
at java.util.HashMap$KeyIterator.next(HashMap.java:833)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:350)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.loadSelectedBaseMap(BaseMapSourcesManager.java:398)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:278)
at android.app.Activity.performCreate(Activity.java:5293)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
... 11 more
java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:808)
at java.util.HashMap$KeyIterator.next(HashMap.java:833)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getSelectedBaseMapTable(BaseMapSourcesManager.java:350)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.loadSelectedBaseMap(BaseMapSourcesManager.java:398)
at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onCreate(MapviewActivity.java:278)
at android.app.Activity.performCreate(Activity.java:5293)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
at dalvik.system.NativeStart.main(Native Method)

LOGCAT=--------- beginning of /dev/log/system
--------- beginning of /dev/log/main

**Comment by moovida** [comment]
done
