### ISSUE TITLE
FROM ACRA: chart error

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#377]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=5.0.2
PHONE_MODEL=SM-G360F
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
at eu.hydrologis.geopaparazzi.ui.activities.ProfileChartActivity.scrollElev(ProfileChartActivity.java:545)
at eu.hydrologis.geopaparazzi.ui.activities.ProfileChartActivity.onTouch(ProfileChartActivity.java:489)
at android.view.View.dispatchTouchEvent(View.java:8475)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2583)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2315)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2583)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2315)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2583)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2315)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2583)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2315)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2502)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1729)
at android.app.Activity.dispatchTouchEvent(Activity.java:2786)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2463)
at android.view.View.dispatchPointerEvent(View.java:8671)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4096)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3959)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3521)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3574)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3540)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3650)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3548)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3707)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3521)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3574)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3540)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3548)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3521)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5793)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5767)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5738)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5883)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5854)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5906)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:548)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5608)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)

**Comment by moovida** [comment]
done
