### ISSUE TITLE
FROM ACRA: case of missing gps

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#379]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=5.1.1
PHONE_MODEL=iRULU X11
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start service eu.geopaparazzi.library.gps.GpsService@399c029 with Intent { cmp=eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.gps.GpsService }: java.lang.IllegalArgumentException: provider doesn't exist: gps

at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
at android.app.ActivityThread.access$2100(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalArgumentException: provider doesn't exist: gps
at android.os.Parcel.readException(Parcel.java:1550)
at android.os.Parcel.readException(Parcel.java:1499)
at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:582)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java:884)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java:476)
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:297)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:211)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
... 9 more
java.lang.IllegalArgumentException: provider doesn't exist: gps
at android.os.Parcel.readException(Parcel.java:1550)
at android.os.Parcel.readException(Parcel.java:1499)
at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:582)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java:884)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java:476)
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:297)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:211)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
at android.app.ActivityThread.access$2100(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
should be solved...
