### ISSUE TITLE
FROM ACRA: SecurityException on GPSservice

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#380]
APP_VERSION_CODE=78
APP_VERSION_NAME=5.1.2
ANDROID_VERSION=6.0.1
PHONE_MODEL=Lenovo PB1-750M
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start service eu.geopaparazzi.library.gps.GpsService@f3c60d9 with Intent { cmp=eu.hydrologis.geopaparazzi/eu.geopaparazzi.library.gps.GpsService (has extras) }: java.lang.SecurityException
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
at android.app.ActivityThread.access$2200(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.SecurityException
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:292)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:211)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
... 8 more
java.lang.SecurityException
at eu.geopaparazzi.library.gps.GpsService.registerForLocationUpdates(GpsService.java:292)
at eu.geopaparazzi.library.gps.GpsService.onStartCommand(GpsService.java:211)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
at android.app.ActivityThread.access$2200(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
done
