### ISSUE TITLE
Mapsforge maps problem

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#406]
The new mapsforge maps seems to have a backward compatibility problem and often miss tiles.

**Comment by gvghia** [comment]
Found some errors in the log and assume they are part of the problem:
"1","1494626673892","UU;ERROR_GEOPAPARAZZI;MAPDATABASEHANDLER: MapDatabaseHandler[/storage/emulated/0/maps/centreml.map]: Could not open the map database: /storage/emulated/0/maps/centreml.map"
"2","1494626673926","UU;ERROR_GEOPAPARAZZI;MAPDATABASEHANDLER: java.io.IOException: Could not open the map database: /storage/emulated/0/maps/centreml.map
	at eu.geopaparazzi.mapsforge.databasehandlers.MapDatabaseHandler.open(MapDatabaseHandler.java:99)
	at eu.geopaparazzi.mapsforge.databasehandlers.MapDatabaseHandler.<init>(MapDatabaseHandler.java:65)
	at eu.geopaparazzi.mapsforge.databasehandlers.MapDatabaseHandler.getHandlerForFile(MapDatabaseHandler.java:81)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.collectTablesFromFile(BaseMapSourcesManager.java:252)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.addBaseMapsFromFile(BaseMapSourcesManager.java:214)
	at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$2.doBackgroundWork(SourcesTreeListActivity.java:218)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:118)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:61)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
"
"3","1494626673944","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference"
"4","1494626673963","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at eu.geopaparazzi.library.core.maps.BaseMap.hashCode(BaseMap.java:114)
	at java.util.Collections.secondaryHash(Collections.java:3405)
	at java.util.HashMap.put(HashMap.java:385)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.saveToBaseMap(BaseMapSourcesManager.java:325)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.addBaseMapsFromFile(BaseMapSourcesManager.java:215)
	at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$2.doBackgroundWork(SourcesTreeListActivity.java:218)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:118)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:61)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
"
"5","1494629133322","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference"
"6","1494629133364","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at eu.geopaparazzi.library.core.maps.BaseMap.hashCode(BaseMap.java:114)
	at java.util.Collections.secondaryHash(Collections.java:3405)
	at java.util.HashMap.get(HashMap.java:300)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.setSelectedBaseMap(BaseMapSourcesManager.java:386)
	at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$4.onChildClick(SourcesTreeListActivity.java:415)
	at android.widget.ExpandableListView.handleItemClick(ExpandableListView.java:716)
	at android.widget.ExpandableListView.performItemClick(ExpandableListView.java:655)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
	at android.widget.AbsListView$3.run(AbsListView.java:3833)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5219)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
"
"7","1494630703288","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: No value for title"
"8","1494630703321","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: org.json.JSONException: No value for title
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at eu.geopaparazzi.library.core.maps.BaseMap.fromJsonString(BaseMap.java:75)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMapsFromPreferences(BaseMapSourcesManager.java:180)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMaps(BaseMapSourcesManager.java:149)
	at eu.hydrologis.geopaparazzi.ui.fragments.GeopaparazziActivityFragment$1.run(GeopaparazziActivityFragment.java:153)
	at java.lang.Thread.run(Thread.java:818)
"
"9","1494631885299","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: No value for title"
"10","1494631885331","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: org.json.JSONException: No value for title
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at eu.geopaparazzi.library.core.maps.BaseMap.fromJsonString(BaseMap.java:75)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMapsFromPreferences(BaseMapSourcesManager.java:180)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMaps(BaseMapSourcesManager.java:149)
	at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$1.doBackgroundWork(SourcesTreeListActivity.java:140)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:118)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:61)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
"
"11","1494631896648","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: No value for title"
"12","1494631896679","UU;ERROR_GEOPAPARAZZI;BASEMAPSOURCESMANAGER: org.json.JSONException: No value for title
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at eu.geopaparazzi.library.core.maps.BaseMap.fromJsonString(BaseMap.java:75)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMapsFromPreferences(BaseMapSourcesManager.java:180)
	at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.getBaseMaps(BaseMapSourcesManager.java:149)
	at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$1.doBackgroundWork(SourcesTreeListActivity.java:140)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:118)
	at eu.geopaparazzi.library.util.StringAsyncTask.doInBackground(StringAsyncTask.java:61)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
"
"13","1494659703533","UU;INFO;DAOSPATIALIE: JavaSqliteDescription[sqlite[3.8.10.2],spatialite[4.4.0-RC1],proj4[Rel. 4.9.3, 15 August 2016],geos[3.6.1-CAPI-1.10.1 r0],spatialite_properties[HasIconv[1],HasMathSql[1],HasGeoCallbacks[0],HasProj[1],HasGeos[1],HasGeosAdvanced[1],HasGeosTrunk[0],HasRtTopo[1],HasLibXML2[1],HasEpsg[1],HasFreeXL[0],HasGeoPackage[1],target_cpu[x86]],rasterlite2_properties[1.6.10]]] recovery_mode[STRICT]"
"14","1494674218898","UU;INFO;DAOSPATIALIE: JavaSqliteDescription[sqlite[3.8.10.2],spatialite[4.4.0-RC1],proj4[Rel. 4.9.3, 15 August 2016],geos[3.6.1-CAPI-1.10.1 r0],spatialite_properties[HasIconv[1],HasMathSql[1],HasGeoCallbacks[0],HasProj[1],HasGeos[1],HasGeosAdvanced[1],HasGeosTrunk[0],HasRtTopo[1],HasLibXML2[1],HasEpsg[1],HasFreeXL[0],HasGeoPackage[1],target_cpu[x86]],rasterlite2_properties[1.6.10]]] recovery_mode[STRICT]"
"15","1495179645235","UU;INFO;DAOSPATIALIE: JavaSqliteDescription[sqlite[3.8.10.2],spatialite[4.4.0-RC1],proj4[Rel. 4.9.3, 15 August 2016],geos[3.6.1-CAPI-1.10.1 r0],spatialite_properties[HasIconv[1],HasMathSql[1],HasGeoCallbacks[0],HasProj[1],HasGeos[1],HasGeosAdvanced[1],HasGeosTrunk[0],HasRtTopo[1],HasLibXML2[1],HasEpsg[1],HasFreeXL[0],HasGeoPackage[1],target_cpu[x86]],rasterlite2_properties[1.6.10]]] recovery_mode[STRICT]"
Seems like sometimes expected data is not present or object is not in place.

**Comment by moovida** [comment]
Nope, the problem you describe is a different one and I assume that it is due to a corrupted .map file. If you want, open a different issue, but first try with a different map file. If you are not able to, also clean the application data cache (in the android application list).

The bug of this issue has been solved in changeset 89ae702
