### ISSUE TITLE
Out of memory crashes due to images thumbnails

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#415]
At the moment they are first cause of crashes. Images that get even 16MB in file size and obviously expanded in memory to create thumbnails, they crash the app.

If the resolution of the app is lowered, everything works properly.

Will have to understand what is the best way to handle this.

For sure we will have to add a message warning for images that are taken at too high resolution.

**Comment by moovida** [comment]
APP_VERSION_CODE=82
APP_VERSION_NAME=5.4.0
ANDROID_VERSION=7.0
PHONE_MODEL=SM-A520F
CUSTOM_DATA=
STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 60MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
at eu.geopaparazzi.library.images.ImageUtilities.getImageAndThumbnailFromPath(ImageUtilities.java:146)
at eu.geopaparazzi.library.camera.CameraNoteActivity.doSaveData(CameraNoteActivity.java:89)
at eu.geopaparazzi.library.camera.AbstractCameraActivity.onActivityResult(AbstractCameraActivity.java:144)
at android.app.Activity.dispatchActivityResult(Activity.java:7292)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
at android.app.ActivityThread.-wrap22(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by moovida** [comment]
Solved with missign largeheap support and a dialog that warns the user to use too high image quality.
