### ISSUE TITLE
From ACRA - no such table: gpslogs

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#416]
APP_VERSION_CODE=82 APP_VERSION_NAME=5.4.0 ANDROID_VERSION=6.0 PHONE_MODEL=Redmi Note 4 CUSTOM_DATA= STACK_TRACE=android.database.sqlite.SQLiteException: no such table: gpslogs (code 1): , while compiling: select l._id AS _id, p.color, p.width, p.visible from gpslogs l, gpslogsproperties p where l._id = p.logid order by _id at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896) at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507) at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588) at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58) at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37) at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44) at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346) at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285) at eu.geopaparazzi.core.database.DaoGpsLog.getGpslogOverlays(DaoGpsLog.java:478) at eu.geopaparazzi.core.mapview.MapviewActivity.readData(MapviewActivity.java:490) at eu.geopaparazzi.core.mapview.MapviewActivity.onWindowFocusChanged(MapviewActivity.java:583) at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:128) at com.android.internal.policy.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:3294) at android.view.View.dispatchWindowFocusChanged(View.java:9664) at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1225) at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3858) at android.os.Handler.dispatchMessage(Handler.java:111) at android.os.Looper.loop(Looper.java:207) at android.app.ActivityThread.main(ActivityThread.java:5791) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) LOGCAT=--------- beginning of system --------- beginning of main

**Comment by moovida** [comment]
added defensive catch - this is due to some db corruption
