### ISSUE TITLE
From ACRA -  intento activing the list Spatiale

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#418]
Hello
This error ocurrer when I intento activing the list Spatiale data using a Huawei mobile...What I resolved This problem?
This is de code error

APP_VERSION_CODE=80
APP_VERSION_NAME=5.3.0
ANDROID_VERSION=5.0.1
PHONE_MODEL=ALE-L02
CUSTOM_DATA=
STACK_TRACE=java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at android.util.PathParser$PathDataNode.addCommand(PathParser.java:330)
        at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
        at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
        at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
        at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
        at android.widget.ImageView.onDraw(ImageView.java:1166)
        at android.view.View.draw(View.java:15038)
        at android.view.View.updateDisplayListIfDirty(View.java:13959)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.draw(View.java:15041)
        at android.view.View.updateDisplayListIfDirty(View.java:13959)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
        at android.view.View.updateDisplayListIfDirty(View.java:13919)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
        at android.view.View.updateDisplayListIfDirty(View.java:13919)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
        at android.view.View.updateDisplayListIfDirty(View.java:13919)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
        at android.view.View.updateDisplayListIfDirty(View.java:13919)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
        at android.view.View.updateDisplayListIfDirty(View.java:13919)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:284)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:290)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:342)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2574)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2399)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1087)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6040)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
        at android.view.Choreographer.doCallbacks(Choreographer.java:606)
        at android.view.Choreographer.doFrame(Choreographer.java:575)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5538)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

LOGCAT=

**Comment by moovida** [comment]
I can't reproduce this, might be due to the android version?

**Comment by moovida** [comment]
close it for now
