### ISSUE TITLE
From ACRA - BaseMap

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#420]
APP_VERSION_CODE=82
APP_VERSION_NAME=5.4.0
ANDROID_VERSION=6.0.1
PHONE_MODEL=SM-N910F
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
at eu.geopaparazzi.library.core.maps.BaseMap.hashCode(BaseMap.java:114)
at java.util.Collections.secondaryHash(Collections.java:3427)
at java.util.HashMap.remove(HashMap.java:616)
at eu.geopaparazzi.mapsforge.BaseMapSourcesManager.removeBaseMap(BaseMapSourcesManager.java:233)
at eu.geopaparazzi.mapsforge.sourcesview.SourcesTreeListActivity$5$1.run(SourcesTreeListActivity.java:480)
at java.lang.Thread.run(Thread.java:818)

**Comment by moovida** [comment]
added log
