### ISSUE TITLE
From ACRA - MapWorker

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#421]
APP_VERSION_CODE=82
APP_VERSION_NAME=5.4.0
ANDROID_VERSION=4.4.2
PHONE_MODEL=GT-N7100
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:76)
at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)

**Comment by moovida** [comment]
added checks
