### ISSUE TITLE
From ACRA - TileCache

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#422]
APP_VERSION_CODE=82
APP_VERSION_NAME=5.4.0
ANDROID_VERSION=5.1.1
PHONE_MODEL=HUAWEI SCL-L01
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.mapsforge.android.maps.mapgenerator.TileCache.containsKey(org.mapsforge.android.maps.mapgenerator.MapGeneratorJob)' on a null object reference
at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:76)
at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
duplicate of #421
