### ISSUE TITLE
From ACRA - no such table: gpslogs

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#423]
APP_VERSION_CODE=79
APP_VERSION_NAME=5.2.0
ANDROID_VERSION=7.0
PHONE_MODEL=MHA-L29
CUSTOM_DATA=
STACK_TRACE=android.database.sqlite.SQLiteException: no such table: gpslogs (Sqlite code 1): , while compiling: select l._id AS _id, p.color, p.width, p.visible from gpslogs l, gpslogsproperties p where l._id = p.logid order by _id, (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:899)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:510)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1397)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1331)
        at eu.hydrologis.geopaparazzi.database.DaoGpsLog.getGpslogOverlays(DaoGpsLog.java:478)
        at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.readData(MapviewActivity.java:491)
        at eu.hydrologis.geopaparazzi.mapview.MapviewActivity.onWindowFocusChanged(MapviewActivity.java:584)
        at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:128)
        at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1513)
        at android.view.View.dispatchWindowFocusChanged(View.java:10245)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1192)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3860)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

LOGCAT=--------- beginning of main

**Comment by moovida** [comment]
duplicate of #416
