### ISSUE TITLE
unable to open form image thumbs

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#491]
05-12 09:42:08.878 28403-28403/eu.hydrologis.geopaparazzi I/GPLOG_ERROR: android.os.FileUriExposedException: file:///storage/emulated/0/geopaparazzi/temp/tmp_gp_image.jpg exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4487)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4445)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4806)
        at android.app.Activity.startActivity(Activity.java:4774)
        at eu.geopaparazzi.library.forms.views.GPictureView$2.onClick(GPictureView.java:223)
        at android.view.View.performClick(View.java:6294)

**Comment by moovida** [comment]
This turned out to need the provider to be used:

```
                            Uri imageUri = FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".library.fileprovider", imageFile);
                            intent.setDataAndType(imageUri, "image/*"); //$NON-NLS-1$
                            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
```

fixed in ef8d84c
