### ISSUE TITLE
issues when taking pictures

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#503]
A user reported that pictures are not put in the db.
Might be due to missing compass.

The error in the log:

UU;ERROR_GEOPAPARAZZI;CAMERANOTEACTIVITY: java.io.IOException: NOT NULL constraint failed: images.azim (code 1299)
	at eu.geopaparazzi.core.database.DaoImages.addImage(DaoImages.java:182)
	at eu.geopaparazzi.library.camera.CameraNoteActivity.doSaveData(CameraNoteActivity.java:116)
	at eu.geopaparazzi.library.camera.AbstractCameraActivity.onActivityResult(AbstractCameraActivity.java:144)
	at android.app.Activity.dispatchActivityResult(Activity.java:6607)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3875)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3922)
	at android.app.ActivityThread.access$1500(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5608)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

UU;ERROR_GEOPAPARAZZI;CAMERANOTEACTIVITY: NOT NULL constraint failed: images.azim (code 1299)

**Comment by moovida** [comment]
fixed
