### ISSUE TITLE
From ACRA: delete note

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#516]
```
PP_VERSION_CODE=90
CUSTOM_DATA=
APP_VERSION_NAME=5.6.0
PHONE_MODEL=SM-A510F
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at eu.geopaparazzi.core.database.DaoNotes.deleteComplexNote(DaoNotes.java:225)
at eu.geopaparazzi.core.ui.activities.NotesListActivity$5$1.onPostExecute(NotesListActivity.java:525)
at eu.geopaparazzi.core.ui.activities.NotesListActivity$5$1.onPostExecute(NotesListActivity.java:517)
at android.os.AsyncTask.finish(AsyncTask.java:660)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by moovida** [comment]
Seems to be related to when a user pushes back button without editing a not. That might cause the crash.

**Comment by moovida** [comment]
related to #504
