### ISSUE TITLE
From ACRA: NPE in MapviewActivity

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#568]
```
STACK_TRACE=java.lang.RuntimeException: Unable to destroy activity {eu.hydrologis.geopaparazzi/eu.geopaparazzi.core.mapview.MapviewActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.mapsforge.android.maps.mapgenerator.TileCache.destroy()' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3765)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3783)
at android.app.ActivityThread.access$1400(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5351)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.mapsforge.android.maps.mapgenerator.TileCache.destroy()' on a null object reference
at org.mapsforge.android.maps.MapView.destroy(MapView.java:724)
at org.mapsforge.android.maps.MapActivity.destroyMapViews(MapActivity.java:64)
at org.mapsforge.android.maps.MapActivity.onDestroy(MapActivity.java:91)
at eu.geopaparazzi.core.mapview.MapviewActivity.onDestroy(MapviewActivity.java:484)
at android.app.Activity.performDestroy(Activity.java:6199)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1140)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3752)
... 10 more
java.lang.NullPointerException: Attempt to invoke interface method 'void org.mapsforge.android.maps.mapgenerator.TileCache.destroy()' on a null object reference
at org.mapsforge.android.maps.MapView.destroy(MapView.java:724)
at org.mapsforge.android.maps.MapActivity.destroyMapViews(MapActivity.java:64)
at org.mapsforge.android.maps.MapActivity.onDestroy(MapActivity.java:91)
at eu.geopaparazzi.core.mapview.MapviewActivity.onDestroy(MapviewActivity.java:484)
at android.app.Activity.performDestroy(Activity.java:6199)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1140)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3752)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3783)
at android.app.ActivityThread.access$1400(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5351)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by moovida** [comment]
Tried to fix in a8188bf6
