### ISSUE TITLE
From ACRA: Unable to resume activity 

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#569]
```
PHONE_MODEL=ASUS_X018D
APP_VERSION_CODE=91
ANDROID_VERSION=7.0
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {eu.hydrologis.geopaparazzi/eu.hydrologis.geopaparazzi.GeopaparazziActivity}: java.lang.IllegalArgumentException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3526)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3566)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:208)
at android.app.ActivityThread.main(ActivityThread.java:6267)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.IllegalArgumentException
at android.os.Parcel.readException(Parcel.java:1687)
at android.os.Parcel.readException(Parcel.java:1636)
at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5629)
at android.app.Activity.isTopOfTask(Activity.java:6003)
at android.app.Activity.onResume(Activity.java:1276)
at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
at eu.geopaparazzi.core.GeopaparazziCoreActivity.onResume(GeopaparazziCoreActivity.java:107)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
at android.app.Activity.performResume(Activity.java:6810)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3497)
... 8 more
java.lang.IllegalArgumentException
at android.os.Parcel.readException(Parcel.java:1687)
at android.os.Parcel.readException(Parcel.java:1636)
at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5629)
at android.app.Activity.isTopOfTask(Activity.java:6003)
at android.app.Activity.onResume(Activity.java:1276)
at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
at eu.geopaparazzi.core.GeopaparazziCoreActivity.onResume(GeopaparazziCoreActivity.java:107)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
at android.app.Activity.performResume(Activity.java:6810)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3497)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3566)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:208)
at android.app.ActivityThread.main(ActivityThread.java:6267)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

APP_VERSION_NAME=5.6.1
LOGCAT=--------- beginning of main
CUSTOM_DATA=
```

**Comment by moovida** [comment]
cleaned up code for this
