### ISSUE TITLE
Run release 6.1.1 app not work

### ISSUE THREAD

**Issue by paulqwerty1** [geopaparazzi/geopaparazzi#663]
Hi!

I'have download the source code from release 6.1.1 and when i tried to load a .gpkg file from layer screen i received the next error:

Do you know if i need to download somethin elses? Thanks!

`Process: eu.hydrologis.geopaparazzi, PID: 5094
    java.lang.UnsatisfiedLinkError: No implementation found for void jsqlite.Database.internal_init() (tried Java_jsqlite_Database_internal_1init and Java_jsqlite_Database_internal_1init__)
        at jsqlite.Database.internal_init(Native Method)
        at jsqlite.Database.<clinit>(Database.java:950)
        at org.hortonmachine.dbs.spatialite.android.GPSpatialiteDb.open(GPSpatialiteDb.java:96)
        at org.hortonmachine.dbs.geopackage.GeopackageCommonDb.open(GeopackageCommonDb.java:126)
        at eu.geopaparazzi.map.gui.MapLayerListFragment.onActivityResult(MapLayerListFragment.java:615)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:8304)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.hortonmachine.dbs.spatialite.android.GPConnection.close()' on a null object reference
        at org.hortonmachine.dbs.spatialite.android.GPSpatialiteDb.close(GPSpatialiteDb.java:114)
        at org.hortonmachine.dbs.geopackage.GeopackageCommonDb.close(GeopackageCommonDb.java:662)
        at eu.geopaparazzi.map.gui.MapLayerListFragment.onActivityResult(MapLayerListFragment.java:614)`

**Comment by moovida** [comment]
HI @paulqwerty1 , you do not seem to have loaded the native libraries of spatialite properly. Without those geopackage can't be opened.

I would suggest you to check out the project SMASH ( https://github.com/geopaparazzi/smash/ ) by the same authors. Geopaparazzi is no longer actively developed.

**Comment by paulqwerty1** [comment]
Hi @moovida ! Thanks for your answer.

How can i load the native libraries of spatialite propertly? I've check your SMASH project but geopaparazzi is better for me now. 
I've supposed this load was on the app. I've download Play Store Geopaparazzi and I'm able to load .gpkg without problems.

**Comment by moovida** [comment]
The libs should load automatically, they are in the project: https://github.com/geopaparazzi/geopaparazzi/tree/master/geopaparazzi_map/jniLibs

If they do not, then it might be some loader issue, but I would not have any idea about it. Maybe a verbose log at startup might help you find the issue.

**Comment by paulqwerty1** [comment]
Thank you @moovida I don't know what's happen because not error log is shown. I'll continue find a solution. I can see all so libraries so i don't understand the problem.

Thanks!

**Comment by paulqwerty1** [comment]
I added this ndk { abiFilters "armeabi-v7a" } in gradle file and now it works. thanks!

**Comment by moovida** [comment]
Thanks for the solution. Would you mind to make a pull request for this? Would be great to have it for everyone with the same problem :-)
